Ot 125 66,67,68,69
alkemyTech/OT125-SERVER pull request #27
Opened 2022-02-05 15:00 UTC by juanco713

- ticket 66 => Migration created to add new columns to Organizations.
- tickets 67 => Endpoint organizations/public modified to get urls from organizations.
- ticket 68 => it was already done.
- ticket 69 => Endpoint to create a new testimonial.

2022-02-05 22:12 UTC, thadek requested changes

2022-02-05 22:12 UTC, thadek commented on controllers/testimonials.js
> +      const data = await repo.createTestimonial(req.body);
responseHandler devuelve el formato de respuesta con 2 atributos, statusCode y response. Cuando recibis el objeto en el controller tenes que adaptarlo de la siguiente forma:
res.status(data.status).json(data.response)

2022-02-05 22:12 UTC, thadek commented on middleware/testimonialValidation.js
> +    (req, res, next) => {
[Sugerencia] : Acá podes importar errFilter como middleware, hace exactamente lo mismo

2022-02-08 22:41 UTC, thadek approved these changes

2022-02-08 22:43 UTC, sebastos23 approved these changes

2022-02-08 22:44 UTC, FacuBar approved these changes

2022-02-08 22:44 UTC, RominaSaravia approved these changes

2022-02-08 22:45 UTC, merged