Ot125 70 71 testimonials endpoint delete update
alkemyTech/OT125-SERVER pull request #35
Opened 2022-02-08 19:55 UTC by xiomaraOcampo

2022-02-08 23:32 UTC, thadek requested changes

2022-02-08 23:32 UTC, thadek commented on controllers/testimonials.js
> +      res.json(data);
Formato válido para responseHandler:
res.json(data.response).status(data.statusCode);

2022-02-08 23:32 UTC, thadek commented on controllers/testimonials.js
> +      const { id } = req.params;
Error no controlado por un try catch, puede crashear la app
Opción 1: usar try-catch
Opcion 2: validar previamente desde Express validator

2022-02-08 23:32 UTC, thadek commented on routes/testimonials.js
> +//router.use(auth, isAdmin);
Middleware isAdmin y auth dependen uno del otro en chain, ya que auth carga en la request el objeto del payload JWT con el roleId del usuario. No poner ambos crashea la app al momento de hacer una request en ese endpoint

2022-02-09 01:13 UTC, RominaSaravia approved these changes

2022-02-09 01:13 UTC, thadek approved these changes

2022-02-09 01:13 UTC, sebastos23 approved these changes

2022-02-09 01:13 UTC, DarioSilva7 approved these changes

2022-02-09 01:13 UTC, FacuBar approved these changes

2022-02-09 01:13 UTC, merged