Ot125 87 members paginacion
alkemyTech/OT125-SERVER pull request #52
Opened 2022-02-22 00:43 UTC by RominaSaravia

## Summary:
Endpoint Get all members --> Pagination added.

Example:
![image](https://user-images.githubusercontent.com/61885187/155043055-2bc9a0b1-184d-463f-90b7-a561c4d9284e.png)

2022-02-22 23:41 UTC, thadek approved these changes

2022-02-22 23:42 UTC, thadek requested changes
Esta a main hecho el merge, no a develop

2022-02-22 23:55 UTC, thadek approved these changes

2022-02-23 02:02 UTC, sebastos23 approved these changes

2022-02-23 02:02 UTC, xiomaraOcampo approved these changes

2022-02-23 02:02 UTC, merged